apiVersion: v1
kind: Service
metadata:
  name: treeapi-svc
  namespace: treeapi
  labels:
    app: treeapi
spec:
  selector:
    app: treeapi
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000