apiVersion: networking.k8s.io/v1
kind: Ingress   
metadata: 
  name: treeapi-ingress
  namespace: treeapi
spec:
  rules:
  - host: tree-api.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: treeapi-svc
            port:
              number: 8000